name:                barrier
version:             0.1.0.0
github:              "githubuser/barrier"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/barrier#readme>

library:
  source-dirs: src
  ghc-options: 
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wmissing-import-lists
    - -Wcompat
  dependencies:
  - base >= 4.7 && < 5
  - Spock
  - aeson
  - async
  - bytestring
  - connection
  - data-default-class
  - errors
  - foreign-store
  - github
  - github-webhooks
  - http-client
  - http-client-tls
  - http-types
  - hvect
  - microlens-platform
  - mtl
  - pcre-heavy
  - random
  - req
  - safe-exceptions
  - simple-logger
  - stm
  - stm-chans
  - text
  - uri-bytestring
  - vector
  - wai
  - wai-extra
  - warp
  - containers
  - aeson-casing
  - aeson-better-errors
  - string-conversions
  - generic-lens

executables:
  barrier:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - barrier

tests:
  barrier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
